### ISSUE TITLE
Can I get my access level reduced from admin to something more appropriate?

### ISSUE THREAD

**Issue by dcelisgarza** [Fortran-FOSS-Programmers/WenOOF#10]
Hello,

I just joined the organisation and team and haven't yet used GitHub on collaborative efforts---so I'm a bit of a noob. As such, I got alarmed when the approval confirmation email stated that I have admin privileges on this repo. I don't feel comfortable having such power with such little experience and how little interaction I've had with you guys. May I be relegated to something more appropriate to my station? Maybe when I've earned my stripes I'll feel ready for such responsibilities.

Cheers,
Daniel

**Comment by zbeekman** [comment]
Sure, I'll de-escalate your privileges.

**Comment by zbeekman** [comment]
That should be resolved. Let me know if you have any questions.

**Comment by szaghi** [comment]
@dcelisgarza 

Hi Daniel, welcome aboard!

Do not worry about eventual git-mistakes, there are good chances to revert back any mistakes, moreover @zbeekman is very close to Gandalf, he save us always!

Cheers.

P.S. Feel free to create new repo, ask questions (we have a chat [here](https://gitter.im/Fortran-FOSS-Programmers/General-Discussion)) join current repo. WenOOF is currently stalled due to the fact I am busy with the _official work_, but into this [fork](https://github.com/giacombum/WenOOF) one of us is going over.

**Comment by rouson** [comment]
I think I'll have to get @zbeekman a purple wizard's hat. ;) 

![sourcery-logo- rgb-low-rez 2](https://cloud.githubusercontent.com/assets/13108868/19918319/5f648786-a087-11e6-828b-95ee954af217.jpg)

**Comment by szaghi** [comment]
@rouson If you will give the purple wizard's hat to our Gandalf, I can try to find the walking stick but I am not _raining man_ as you :smile:

**Comment by dcelisgarza** [comment]
Thanks guys, I feel much better now. I'm thinking of starting a repo for arbitrary numerical differentiation, and probably one on dynamic remeshing. But I have to get the details of my PhD down first (first year is mostly courses), so it may take a little while.

**Comment by szaghi** [comment]
@dcelisgarza 

Daniel, this is very nice to read, many of us work on numerical simulations. 

During your studies I suggest to take a look at @jacobwilliams and @cmacmackin works, just to cite the first two coming into my mind. Then, most of us are involved into such applications (see the list of members of the group: aside me :smile: , all are really great). You have already known Zaak, but for example Damian has great experience (he is more mature than how he looks like :smile: ), he can teach us a lot... 

P.S. @zbeekman the last months were terrible for me, I forget to ask you for your Ph.D. thesis, I am sorry... have you defended it?

**Comment by dcelisgarza** [comment]
Yeah I've known about a few of you guys for a while, since back before I started applying to gradschool but I didn't know you all collaborated. I think it's an awesome grassroots thing, I like that it's all in the public domain and no institution can claim it as their own. I'm still miffed that Oxford claims ownership of the things I produce, so I'll limit what they can lay claim to by contributing here and citing it in my thesis/publications.

**Comment by cmacmackin** [comment]
@dcelisgarza 
As a student at Oxford, that is news to me. My supervisor told me to use whatever license I want for my software and that there wasn't an issue just posting it to GitHub.

**Comment by dcelisgarza** [comment]
@cmacmackin 
Yeah we had a talk at the materials department about it by an MPLS representative. Fortunately we do have the freedom you mentioned.

**Comment by szaghi** [comment]
@dcelisgarza  

I do not know if Oxford has a _code of conduct_, it seems to be case-dependent. However, here we do not stick on any rules, our collaboration is based even on simple sharing of idea or discussions, e.g. see [this](https://github.com/Fortran-FOSS-Programmers/Best_Practices/issues/15). If you have copyrights-issue do not worry about it, we are happy just to talk with you, you do **not** need to share any SLOC of your codes :smile: and you can use our available resources if they are of some help.

Cheers.

**Comment by dcelisgarza** [comment]
@szaghi

It's not really an issue if the software is sourced from somewhere. So the trick is to develop for an open source project and then use it in your project. Developing in-house code and then making it open source without express permission is an issue. That's easily avoided by developing for personal or open source repositories and using them in our work. Technically that has to be in our own time but no one's gonna scrutinise that closely, plus it can be chalked up as porting and modifying source code.
